services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/app # すべてのファイルを共有
      - pnpm_store:/app/.pnpm-store # node_modulesは共有しない（コンテナ専用）
      - node_modules:/app/node_modules # node_modulesは共有しない（コンテナ専用）
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: local
    volumes:
      - mysqldata:/var/lib/mysql
volumes:
  pnpm_store:
  node_modules:
  mysqldata:
